export const ALL_PAGES = [
  { id: 'dashboard', label: 'Dashboard', emoji: '🏠' },
  { id: 'todo', label: 'Daily Planner', emoji: '📅' },
  { id: 'calendar', label: 'Monthly Calendar', emoji: '📆' },
  { id: 'journal', label: 'Journal', emoji: '📖' },
  { id: 'books', label: 'My Library', emoji: '📚' },
  { id: 'markdown', label: 'Markdown Creator', emoji: '✍️' },
  { id: 'til', label: 'Today I Learned', emoji: '💡' },
  { id: 'snippets', label: 'Code Snippets', emoji: '💻' },
  { id: 'habits', label: 'Habits Tracker', emoji: '🔥' },
  { id: 'pomodoro', label: 'Pomodoro Timer', emoji: '⏱️' },
  { id: 'vision', label: 'Vision Board', emoji: '🎯' },
  { id: 'exam', label: 'AI Exam Prep', emoji: '🧠' },
  { id: 'mindmap', label: 'Mindmap', emoji: '🗺️' },
  { id: 'drawing', label: 'Drawing Canvas', emoji: '🎨' },
  { id: 'media', label: 'Media Log', emoji: '🎮' },
  { id: 'condition', label: 'Workstation', emoji: '📊' },
  { id: 'utilities', label: 'Utilities', emoji: '🛠️' },
  { id: 'linksaver', label: 'Link Vault', emoji: '🔗' },
  { id: 'tags', label: 'Tag Manager', emoji: '🏷️' },
  { id: 'profile', label: 'Profile', emoji: '👤' },
  { id: 'settings', label: 'Settings', emoji: '⚙️' },
  { id: 'changelog', label: "What's New", emoji: '🚀' },
  { id: 'admin', label: 'Admin Panel', emoji: '🛡️' },
];
