import { type ProjectNode } from '../../../store/types';

export interface ArchitecturePreset {
  key: string;
  name: string;
  category: 'Frontend' | 'Fullstack' | 'Backend' | 'Systems' | 'Monorepo';
  description: string;
  rootName: string;
  tags: string[];
  nodes: ProjectNode[];
}

export const ARCHITECTURE_PRESETS: ArchitecturePreset[] = [
  {
    key: 'react-vite',
    name: 'React 19 + Vite + TypeScript',
    category: 'Frontend',
    description: 'Modern component-driven frontend architecture with Tailwind, custom hooks, and state management.',
    rootName: 'vite-react-app',
    tags: ['react', 'typescript', 'vite', 'tailwind'],
    nodes: [
      { id: 'rv-1', name: 'src', type: 'folder', path: 'src', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rv-2', name: 'components', type: 'folder', path: 'src/components', parentId: 'rv-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rv-3', name: 'ui', type: 'folder', path: 'src/components/ui', parentId: 'rv-2', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rv-4', name: 'Button.tsx', type: 'file', path: 'src/components/ui/Button.tsx', extension: 'tsx', parentId: 'rv-3', content: `import React from 'react';\n\ninterface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {\n  variant?: 'primary' | 'secondary' | 'ghost';\n}\n\nexport const Button: React.FC<ButtonProps> = ({ children, variant = 'primary', ...props }) => {\n  return (\n    <button className={\`btn btn-\${variant}\`} {...props}>\n      {children}\n    </button>\n  );\n};`, createdAt: new Date().toISOString() },
      { id: 'rv-5', name: 'Card.tsx', type: 'file', path: 'src/components/ui/Card.tsx', extension: 'tsx', parentId: 'rv-3', content: `export const Card: React.FC<React.PropsWithChildren> = ({ children }) => (\n  <div className="p-4 rounded-xl border border-zinc-800 bg-zinc-900">{children}</div>\n);`, createdAt: new Date().toISOString() },
      { id: 'rv-6', name: 'hooks', type: 'folder', path: 'src/hooks', parentId: 'rv-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rv-7', name: 'useDebounce.ts', type: 'file', path: 'src/hooks/useDebounce.ts', extension: 'ts', parentId: 'rv-6', content: `import { useState, useEffect } from 'react';\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debounced, setDebounced] = useState(value);\n  useEffect(() => {\n    const handler = setTimeout(() => setDebounced(value), delay);\n    return () => clearTimeout(handler);\n  }, [value, delay]);\n  return debounced;\n}`, createdAt: new Date().toISOString() },
      { id: 'rv-8', name: 'store', type: 'folder', path: 'src/store', parentId: 'rv-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rv-9', name: 'useStore.ts', type: 'file', path: 'src/store/useStore.ts', extension: 'ts', parentId: 'rv-8', content: `import { create } from 'zustand';\n\ninterface AppState {\n  count: number;\n  inc: () => void;\n}\n\nexport const useStore = create<AppState>((set) => ({\n  count: 0,\n  inc: () => set((state) => ({ count: state.count + 1 })),\n}));`, createdAt: new Date().toISOString() },
      { id: 'rv-10', name: 'App.tsx', type: 'file', path: 'src/App.tsx', extension: 'tsx', parentId: 'rv-1', content: `export default function App() {\n  return (\n    <main className="min-h-screen bg-black text-white flex items-center justify-center">\n      <h1 className="text-4xl font-bold">React 19 Starter</h1>\n    </main>\n  );\n}`, createdAt: new Date().toISOString() },
      { id: 'rv-11', name: 'main.tsx', type: 'file', path: 'src/main.tsx', extension: 'tsx', parentId: 'rv-1', content: `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);`, createdAt: new Date().toISOString() },
      { id: 'rv-12', name: 'index.css', type: 'file', path: 'src/index.css', extension: 'css', parentId: 'rv-1', content: `@tailwind base;\n@tailwind components;\n@tailwind utilities;`, createdAt: new Date().toISOString() },
      { id: 'rv-13', name: 'public', type: 'folder', path: 'public', parentId: null, isExpanded: false, createdAt: new Date().toISOString() },
      { id: 'rv-14', name: 'favicon.svg', type: 'file', path: 'public/favicon.svg', extension: 'svg', parentId: 'rv-13', content: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="#3b82f6"/></svg>`, createdAt: new Date().toISOString() },
      { id: 'rv-15', name: 'package.json', type: 'file', path: 'package.json', extension: 'json', parentId: null, content: `{\n  "name": "vite-react-app",\n  "private": true,\n  "version": "0.1.0",\n  "type": "module",\n  "scripts": { "dev": "vite", "build": "tsc -b && vite build" }\n}`, createdAt: new Date().toISOString() },
      { id: 'rv-16', name: 'tsconfig.json', type: 'file', path: 'tsconfig.json', extension: 'json', parentId: null, content: `{\n  "compilerOptions": { "target": "ES2022", "module": "ESNext", "jsx": "react-jsx", "strict": true }\n}`, createdAt: new Date().toISOString() },
      { id: 'rv-17', name: 'vite.config.ts', type: 'file', path: 'vite.config.ts', extension: 'ts', parentId: null, content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});`, createdAt: new Date().toISOString() },
      { id: 'rv-18', name: '.env.example', type: 'file', path: '.env.example', extension: 'env', parentId: null, content: `VITE_API_URL=http://localhost:3000`, createdAt: new Date().toISOString() },
    ],
  },
  {
    key: 'nextjs-app',
    name: 'Next.js 15 App Router Fullstack',
    category: 'Fullstack',
    description: 'Production Next.js 15 App Router structure with Route Handlers, Server Actions, and Auth.',
    rootName: 'next-app-router',
    tags: ['nextjs', 'react', 'fullstack', 'typescript'],
    nodes: [
      { id: 'nx-1', name: 'app', type: 'folder', path: 'app', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'nx-2', name: '(auth)', type: 'folder', path: 'app/(auth)', parentId: 'nx-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'nx-3', name: 'login', type: 'folder', path: 'app/(auth)/login', parentId: 'nx-2', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'nx-4', name: 'page.tsx', type: 'file', path: 'app/(auth)/login/page.tsx', extension: 'tsx', parentId: 'nx-3', content: `export default function LoginPage() {\n  return <div>Login</div>;\n}`, createdAt: new Date().toISOString() },
      { id: 'nx-5', name: 'api', type: 'folder', path: 'app/api', parentId: 'nx-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'nx-6', name: 'health', type: 'folder', path: 'app/api/health', parentId: 'nx-5', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'nx-7', name: 'route.ts', type: 'file', path: 'app/api/health/route.ts', extension: 'ts', parentId: 'nx-6', content: `import { NextResponse } from 'next/server';\n\nexport async function GET() {\n  return NextResponse.json({ status: 'ok', timestamp: new Date().toISOString() });\n}`, createdAt: new Date().toISOString() },
      { id: 'nx-8', name: 'layout.tsx', type: 'file', path: 'app/layout.tsx', extension: 'tsx', parentId: 'nx-1', content: `export default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body className="antialiased bg-zinc-950 text-zinc-100">{children}</body>\n    </html>\n  );\n}`, createdAt: new Date().toISOString() },
      { id: 'nx-9', name: 'page.tsx', type: 'file', path: 'app/page.tsx', extension: 'tsx', parentId: 'nx-1', content: `export default function HomePage() {\n  return <main className="p-8"><h1 className="text-3xl font-bold">Welcome</h1></main>;\n}`, createdAt: new Date().toISOString() },
      { id: 'nx-10', name: 'components', type: 'folder', path: 'components', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'nx-11', name: 'Navbar.tsx', type: 'file', path: 'components/Navbar.tsx', extension: 'tsx', parentId: 'nx-10', content: `export const Navbar = () => <nav className="border-b border-zinc-800 p-4">App</nav>;`, createdAt: new Date().toISOString() },
      { id: 'nx-12', name: 'lib', type: 'folder', path: 'lib', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'nx-13', name: 'db.ts', type: 'file', path: 'lib/db.ts', extension: 'ts', parentId: 'nx-12', content: `export const db = {};`, createdAt: new Date().toISOString() },
      { id: 'nx-14', name: 'package.json', type: 'file', path: 'package.json', extension: 'json', parentId: null, content: `{\n  "name": "next-app",\n  "dependencies": { "next": "^15.0.0", "react": "^19.0.0", "react-dom": "^19.0.0" }\n}`, createdAt: new Date().toISOString() },
      { id: 'nx-15', name: 'tsconfig.json', type: 'file', path: 'tsconfig.json', extension: 'json', parentId: null, content: `{\n  "compilerOptions": { "plugins": [{ "name": "next" }] }\n}`, createdAt: new Date().toISOString() },
    ],
  },
  {
    key: 'express-clean',
    name: 'Node.js Express + TypeScript Clean Arch',
    category: 'Backend',
    description: 'Clean onion architecture with Controllers, Services, Repositories, and Prisma ORM.',
    rootName: 'express-api-service',
    tags: ['nodejs', 'express', 'typescript', 'prisma', 'backend'],
    nodes: [
      { id: 'ex-1', name: 'src', type: 'folder', path: 'src', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'ex-2', name: 'controllers', type: 'folder', path: 'src/controllers', parentId: 'ex-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'ex-3', name: 'user.controller.ts', type: 'file', path: 'src/controllers/user.controller.ts', extension: 'ts', parentId: 'ex-2', content: `import { Request, Response } from 'express';\n\nexport const getUser = async (req: Request, res: Response) => {\n  res.json({ id: req.params.id });\n};`, createdAt: new Date().toISOString() },
      { id: 'ex-4', name: 'services', type: 'folder', path: 'src/services', parentId: 'ex-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'ex-5', name: 'user.service.ts', type: 'file', path: 'src/services/user.service.ts', extension: 'ts', parentId: 'ex-4', content: `export class UserService {\n  async findById(id: string) {\n    return { id, name: 'Alice' };\n  }\n}`, createdAt: new Date().toISOString() },
      { id: 'ex-6', name: 'repositories', type: 'folder', path: 'src/repositories', parentId: 'ex-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'ex-7', name: 'user.repository.ts', type: 'file', path: 'src/repositories/user.repository.ts', extension: 'ts', parentId: 'ex-6', content: `export class UserRepository {}`, createdAt: new Date().toISOString() },
      { id: 'ex-8', name: 'routes', type: 'folder', path: 'src/routes', parentId: 'ex-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'ex-9', name: 'index.ts', type: 'file', path: 'src/routes/index.ts', extension: 'ts', parentId: 'ex-8', content: `import { Router } from 'express';\nexport const router = Router();`, createdAt: new Date().toISOString() },
      { id: 'ex-10', name: 'server.ts', type: 'file', path: 'src/server.ts', extension: 'ts', parentId: 'ex-1', content: `import express from 'express';\nconst app = express();\napp.listen(4000, () => console.log('Running on :4000'));`, createdAt: new Date().toISOString() },
      { id: 'ex-11', name: 'prisma', type: 'folder', path: 'prisma', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'ex-12', name: 'schema.prisma', type: 'file', path: 'prisma/schema.prisma', extension: 'prisma', parentId: 'ex-11', content: `datasource db { provider = "postgresql", url = env("DATABASE_URL") }\ngenerator client { provider = "prisma-client-js" }\n\nmodel User { id String @id @default(uuid()) email String @unique }`, createdAt: new Date().toISOString() },
      { id: 'ex-13', name: 'package.json', type: 'file', path: 'package.json', extension: 'json', parentId: null, content: `{\n  "name": "express-clean-api",\n  "scripts": { "dev": "tsx watch src/server.ts" }\n}`, createdAt: new Date().toISOString() },
    ],
  },
  {
    key: 'fastapi',
    name: 'Python FastAPI + SQLAlchemy + Pydantic',
    category: 'Backend',
    description: 'Scalable FastAPI backend structure with API Routers, Pydantic Schemas, and Alembic migrations.',
    rootName: 'fastapi-backend',
    tags: ['python', 'fastapi', 'sqlalchemy', 'pydantic'],
    nodes: [
      { id: 'fa-1', name: 'app', type: 'folder', path: 'app', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'fa-2', name: 'api', type: 'folder', path: 'app/api', parentId: 'fa-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'fa-3', name: 'v1', type: 'folder', path: 'app/api/v1', parentId: 'fa-2', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'fa-4', name: 'auth.py', type: 'file', path: 'app/api/v1/auth.py', extension: 'py', parentId: 'fa-3', content: `from fastapi import APIRouter\n\nrouter = APIRouter(prefix="/auth", tags=["auth"])\n\n@router.post("/login")\ndef login():\n    return {"token": "sample-jwt"}`, createdAt: new Date().toISOString() },
      { id: 'fa-5', name: 'models', type: 'folder', path: 'app/models', parentId: 'fa-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'fa-6', name: 'user.py', type: 'file', path: 'app/models/user.py', extension: 'py', parentId: 'fa-5', content: `from sqlalchemy import Column, String, Integer\nfrom app.core.database import Base\n\nclass User(Base):\n    __tablename__ = "users"\n    id = Column(Integer, primary_key=True, index=True)\n    email = Column(String, unique=True, index=True)`, createdAt: new Date().toISOString() },
      { id: 'fa-7', name: 'schemas', type: 'folder', path: 'app/schemas', parentId: 'fa-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'fa-8', name: 'user.py', type: 'file', path: 'app/schemas/user.py', extension: 'py', parentId: 'fa-7', content: `from pydantic import BaseModel, EmailStr\n\nclass UserBase(BaseModel):\n    email: EmailStr`, createdAt: new Date().toISOString() },
      { id: 'fa-9', name: 'main.py', type: 'file', path: 'app/main.py', extension: 'py', parentId: 'fa-1', content: `from fastapi import FastAPI\n\napp = FastAPI(title="FastAPI Service")\n\n@app.get("/health")\ndef health():\n    return {"status": "healthy"}`, createdAt: new Date().toISOString() },
      { id: 'fa-10', name: 'requirements.txt', type: 'file', path: 'requirements.txt', extension: 'txt', parentId: null, content: `fastapi>=0.110.0\nuvicorn[standard]>=0.28.0\nsqlalchemy>=2.0.0\npydantic>=2.6.0`, createdAt: new Date().toISOString() },
      { id: 'fa-11', name: 'Dockerfile', type: 'file', path: 'Dockerfile', extension: 'dockerfile', parentId: null, content: `FROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]`, createdAt: new Date().toISOString() },
    ],
  },
  {
    key: 'rust-workspace',
    name: 'Rust Cargo Workspace',
    category: 'Systems',
    description: 'High-performance multi-crate Rust workspace with CLI and Core Engine crates.',
    rootName: 'rust-workspace',
    tags: ['rust', 'cargo', 'tokio', 'systems'],
    nodes: [
      { id: 'rs-1', name: 'crates', type: 'folder', path: 'crates', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rs-2', name: 'engine-core', type: 'folder', path: 'crates/engine-core', parentId: 'rs-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rs-3', name: 'src', type: 'folder', path: 'crates/engine-core/src', parentId: 'rs-2', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rs-4', name: 'lib.rs', type: 'file', path: 'crates/engine-core/src/lib.rs', extension: 'rs', parentId: 'rs-3', content: `pub fn execute_task() -> Result<(), Box<dyn std::error::Error>> {\n    println!("Engine task executed.");\n    Ok(())\n}`, createdAt: new Date().toISOString() },
      { id: 'rs-5', name: 'Cargo.toml', type: 'file', path: 'crates/engine-core/Cargo.toml', extension: 'toml', parentId: 'rs-2', content: `[package]\nname = "engine-core"\nversion = "0.1.0"\nedition = "2021"`, createdAt: new Date().toISOString() },
      { id: 'rs-6', name: 'engine-cli', type: 'folder', path: 'crates/engine-cli', parentId: 'rs-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rs-7', name: 'src', type: 'folder', path: 'crates/engine-cli/src', parentId: 'rs-6', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'rs-8', name: 'main.rs', type: 'file', path: 'crates/engine-cli/src/main.rs', extension: 'rs', parentId: 'rs-7', content: `use engine_core::execute_task;\n\nfn main() {\n    println!("CLI starting...");\n    let _ = execute_task();\n}`, createdAt: new Date().toISOString() },
      { id: 'rs-9', name: 'Cargo.toml', type: 'file', path: 'Cargo.toml', extension: 'toml', parentId: null, content: `[workspace]\nmembers = [\n    "crates/engine-core",\n    "crates/engine-cli"\n]\nresolver = "2"`, createdAt: new Date().toISOString() },
    ],
  },
  {
    key: 'monorepo-turbo',
    name: 'Turborepo TypeScript Monorepo',
    category: 'Monorepo',
    description: 'Enterprise Turborepo monorepo with multiple apps and shared UI and config packages.',
    rootName: 'turbo-monorepo',
    tags: ['turborepo', 'monorepo', 'typescript', 'react'],
    nodes: [
      { id: 'tb-1', name: 'apps', type: 'folder', path: 'apps', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'tb-2', name: 'web', type: 'folder', path: 'apps/web', parentId: 'tb-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'tb-3', name: 'package.json', type: 'file', path: 'apps/web/package.json', extension: 'json', parentId: 'tb-2', content: `{\n  "name": "web",\n  "version": "0.1.0"\n}`, createdAt: new Date().toISOString() },
      { id: 'tb-4', name: 'docs', type: 'folder', path: 'apps/docs', parentId: 'tb-1', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'tb-5', name: 'packages', type: 'folder', path: 'packages', parentId: null, isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'tb-6', name: 'ui', type: 'folder', path: 'packages/ui', parentId: 'tb-5', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'tb-7', name: 'src', type: 'folder', path: 'packages/ui/src', parentId: 'tb-6', isExpanded: true, createdAt: new Date().toISOString() },
      { id: 'tb-8', name: 'index.tsx', type: 'file', path: 'packages/ui/src/index.tsx', extension: 'tsx', parentId: 'tb-7', content: `export * from './Button';`, createdAt: new Date().toISOString() },
      { id: 'tb-9', name: 'turbo.json', type: 'file', path: 'turbo.json', extension: 'json', parentId: null, content: `{\n  "$schema": "https://turbo.build/schema.json",\n  "pipeline": {\n    "build": { "dependsOn": ["^build"], "outputs": [".next/**", "dist/**"] },\n    "lint": { "outputs": [] },\n    "dev": { "cache": false, "persistent": true }\n  }\n}`, createdAt: new Date().toISOString() },
      { id: 'tb-10', name: 'package.json', type: 'file', path: 'package.json', extension: 'json', parentId: null, content: `{\n  "name": "turbo-monorepo",\n  "private": true,\n  "workspaces": ["apps/*", "packages/*"]\n}`, createdAt: new Date().toISOString() },
    ],
  },
];
