import { type ProjectStructure } from '../../../store/types';
import { generateAsciiTree, normalizePath } from './commandEngine';

// Export as ASCII Tree string
export function exportAsAsciiTree(project: ProjectStructure): string {
  return generateAsciiTree(project.rootName || project.name, project.nodes);
}

// Export as Markdown Documentation
export function exportAsMarkdown(project: ProjectStructure): string {
  const tree = exportAsAsciiTree(project);
  const folders = project.nodes.filter((n) => n.type === 'folder').length;
  const files = project.nodes.filter((n) => n.type === 'file').length;

  let md = `# ${project.name}\n\n`;
  if (project.description) {
    md += `> ${project.description}\n\n`;
  }
  md += `## Architecture Overview\n\n- **Root**: \`${project.rootName}\`\n- **Folders**: ${folders}\n- **Files**: ${files}\n- **Template**: ${project.templateType || 'Custom'}\n\n`;
  md += `## Project Tree\n\n\`\`\`text\n${tree}\n\`\`\`\n\n`;

  const filesWithContent = project.nodes.filter((n) => n.type === 'file' && n.content && n.content.trim().length > 0);
  if (filesWithContent.length > 0) {
    md += `## File Specifications & Boilerplates\n\n`;
    filesWithContent.forEach((file) => {
      const ext = file.extension || 'text';
      md += `### \`${file.path}\`\n\n\`\`\`${ext}\n${file.content}\n\`\`\`\n\n`;
    });
  }

  return md;
}

// Export as Bash Shell Script
export function exportAsBashScript(project: ProjectStructure): string {
  const root = project.rootName || 'my-project';
  const folders = project.nodes.filter((n) => n.type === 'folder');
  const files = project.nodes.filter((n) => n.type === 'file');

  const lines: string[] = [
    '#!/usr/bin/env bash',
    `# Scaffold script for ${project.name}`,
    `# Generated by Personal HQ Project Architect`,
    '',
    `mkdir -p "${root}"`,
    `cd "${root}" || exit 1`,
    '',
    '# Create directories',
  ];

  folders.forEach((folder) => {
    lines.push(`mkdir -p "${folder.path}"`);
  });

  lines.push('', '# Create files');
  files.forEach((file) => {
    if (file.content && file.content.trim().length > 0) {
      // Escape EOF safely
      const escaped = file.content.replace(/\\/g, '\\\\').replace(/\$/g, '\\$');
      lines.push(`cat << 'EOF' > "${file.path}"\n${escaped}\nEOF`);
    } else {
      lines.push(`touch "${file.path}"`);
    }
  });

  lines.push('', 'echo "🚀 Project ${project.name} structure created successfully!"');
  return lines.join('\n');
}

// Export as PowerShell Script
export function exportAsPowerShellScript(project: ProjectStructure): string {
  const root = project.rootName || 'my-project';
  const folders = project.nodes.filter((n) => n.type === 'folder');
  const files = project.nodes.filter((n) => n.type === 'file');

  const lines: string[] = [
    `# Scaffold script for ${project.name}`,
    `# Generated by Personal HQ Project Architect`,
    `# Run with: powershell -ExecutionPolicy Bypass -File .\\setup.ps1`,
    '',
    `$Root = "${root}"`,
    `if (!(Test-Path -Path $Root)) { New-Item -ItemType Directory -Path $Root -Force | Out-Null }`,
    `Set-Location -Path $Root`,
    '',
    '# Create directories',
  ];

  folders.forEach((folder) => {
    lines.push(`if (!(Test-Path -Path "${folder.path}")) { New-Item -ItemType Directory -Path "${folder.path}" -Force | Out-Null }`);
  });

  lines.push('', '# Create files');
  files.forEach((file) => {
    if (file.content && file.content.trim().length > 0) {
      const escaped = file.content.replace(/`/g, '``').replace(/"/g, '`"');
      lines.push(`@" \n${escaped}\n"@ | Out-File -FilePath "${file.path}" -Encoding utf8 -Force`);
    } else {
      lines.push(`if (!(Test-Path -Path "${file.path}")) { New-Item -ItemType File -Path "${file.path}" -Force | Out-Null }`);
    }
  });

  lines.push('', 'Write-Host "🚀 Project created successfully in $Root" -ForegroundColor Green');
  return lines.join('\n');
}

// Export as JSON Schema
export function exportAsJson(project: ProjectStructure): string {
  return JSON.stringify(
    {
      name: project.name,
      rootName: project.rootName,
      description: project.description,
      templateType: project.templateType,
      tags: project.tags,
      nodes: project.nodes,
      exportedAt: new Date().toISOString(),
    },
    null,
    2
  );
}

// ── Pure zero-dependency client-side ZIP generator ───────────────────────────
// Creates compliant PKZIP (.zip) standard archive in browser Uint8Array

function crc32(bytes: Uint8Array): number {
  let c = 0 ^ (-1);
  for (let i = 0; i < bytes.length; i++) {
    c = (c >>> 8) ^ CRC_TABLE[(c ^ bytes[i]) & 0xff];
  }
  return (c ^ (-1)) >>> 0;
}

const CRC_TABLE: number[] = (() => {
  const table = new Array<number>(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[n] = c;
  }
  return table;
})();

export function generateProjectZipBlob(project: ProjectStructure): Blob {
  const root = project.rootName || 'project';
  const encoder = new TextEncoder();

  interface ZipEntry {
    name: string;
    isDir: boolean;
    data: Uint8Array;
    crc: number;
    offset: number;
  }

  const entries: ZipEntry[] = [];

  // Add root folder
  entries.push({
    name: `${root}/`,
    isDir: true,
    data: new Uint8Array(0),
    crc: 0,
    offset: 0,
  });

  // Add folder entries
  const folders = project.nodes.filter((n) => n.type === 'folder');
  folders.forEach((f) => {
    entries.push({
      name: `${root}/${normalizePath(f.path)}/`,
      isDir: true,
      data: new Uint8Array(0),
      crc: 0,
      offset: 0,
    });
  });

  // Add file entries
  const files = project.nodes.filter((n) => n.type === 'file');
  files.forEach((f) => {
    const rawContent = f.content || '';
    const bytes = encoder.encode(rawContent);
    entries.push({
      name: `${root}/${normalizePath(f.path)}`,
      isDir: false,
      data: bytes,
      crc: crc32(bytes),
      offset: 0,
    });
  });

  // Build local file headers + body
  const parts: Uint8Array[] = [];
  let currentOffset = 0;

  entries.forEach((entry) => {
    entry.offset = currentOffset;
    const nameBytes = encoder.encode(entry.name);
    const size = entry.data.length;

    // Local file header (30 bytes + name length)
    const header = new Uint8Array(30 + nameBytes.length);
    const view = new DataView(header.buffer);

    view.setUint32(0, 0x04034b50, true); // Local header signature
    view.setUint16(4, 20, true);         // Version needed (2.0)
    view.setUint16(6, 0, true);          // General purpose bit flag
    view.setUint16(8, 0, true);          // Compression method (0 = store)
    view.setUint16(10, 0, true);         // Mod time
    view.setUint16(12, 0, true);         // Mod date
    view.setUint32(14, entry.crc, true); // CRC-32
    view.setUint32(18, size, true);      // Compressed size
    view.setUint32(22, size, true);      // Uncompressed size
    view.setUint16(26, nameBytes.length, true); // File name length
    view.setUint16(28, 0, true);         // Extra field length
    header.set(nameBytes, 30);

    parts.push(header);
    parts.push(entry.data);
    currentOffset += header.length + size;
  });

  // Central Directory start
  const centralDirOffset = currentOffset;
  let centralDirSize = 0;

  entries.forEach((entry) => {
    const nameBytes = encoder.encode(entry.name);
    const size = entry.data.length;

    // Central directory header (46 bytes + name length)
    const cdHeader = new Uint8Array(46 + nameBytes.length);
    const view = new DataView(cdHeader.buffer);

    view.setUint32(0, 0x02014b50, true); // Central header signature
    view.setUint16(4, 20, true);         // Version made by
    view.setUint16(6, 20, true);         // Version needed
    view.setUint16(8, 0, true);          // General purpose bit flag
    view.setUint16(10, 0, true);         // Compression method (0 = store)
    view.setUint16(12, 0, true);         // Mod time
    view.setUint16(14, 0, true);         // Mod date
    view.setUint32(16, entry.crc, true); // CRC-32
    view.setUint32(20, size, true);      // Compressed size
    view.setUint32(24, size, true);      // Uncompressed size
    view.setUint16(28, nameBytes.length, true); // Name length
    view.setUint16(30, 0, true);         // Extra field length
    view.setUint16(32, 0, true);         // Comment length
    view.setUint16(34, 0, true);         // Disk number start
    view.setUint16(36, 0, true);         // Internal file attributes
    view.setUint32(38, entry.isDir ? 0x10 : 0, true); // External file attributes
    view.setUint32(42, entry.offset, true); // Relative offset of local header
    cdHeader.set(nameBytes, 46);

    parts.push(cdHeader);
    currentOffset += cdHeader.length;
    centralDirSize += cdHeader.length;
  });

  // End of Central Directory Record (22 bytes)
  const eocd = new Uint8Array(22);
  const eocdView = new DataView(eocd.buffer);
  eocdView.setUint32(0, 0x06054b50, true); // EOCD signature
  eocdView.setUint16(4, 0, true);          // Number of this disk
  eocdView.setUint16(6, 0, true);          // Disk where central directory starts
  eocdView.setUint16(8, entries.length, true);  // Number of central directory records on this disk
  eocdView.setUint16(10, entries.length, true); // Total central directory records
  eocdView.setUint32(12, centralDirSize, true); // Size of central directory
  eocdView.setUint32(16, centralDirOffset, true); // Offset of start of central directory
  eocdView.setUint16(20, 0, true);          // Comment length
  parts.push(eocd);

  return new Blob(parts as BlobPart[], { type: 'application/zip' });
}

// Trigger ZIP download in browser
export function downloadProjectZip(project: ProjectStructure): void {
  const blob = generateProjectZipBlob(project);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const sanitizedName = (project.rootName || project.name || 'project').toLowerCase().replace(/[^a-z0-9_-]/g, '-');
  link.href = url;
  link.download = `${sanitizedName}.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
