import type { VisionBoard } from '../types';

// Compact, balanced 2-row layout that fits within one screen viewport (height <= 560px)
export const DEFAULT_SEEDED_BOARDS: VisionBoard[] = [
  {
    id: 'board-aesthetic-life',
    title: 'AESTHETIC LIFE',
    subtitle: '2025 Vision',
    category: 'FAVORITES',
    icon: '✨',
    isFavorite: true,
    theme: 'dots',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    nodes: [
      {
        id: 'node-maldives',
        boardId: 'board-aesthetic-life',
        type: 'image',
        title: 'Maldives',
        subtitle: 'Maldives Trip',
        imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=1000&auto=format&fit=crop',
        position: { x: 60, y: 40 },
        size: { width: 300, height: 220 },
        cornerRadius: 20,
        hasShadow: true,
        hasBorder: false,
        tags: ['Maldives trip', 'Travel', 'Ocean'],
        accentColor: '#38bdf8',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'node-design-studio',
        boardId: 'board-aesthetic-life',
        type: 'text',
        title: 'DESIGN STUDIO',
        subtitle: 'Text Node',
        content: 'Curate elevated digital products and spatial environments.',
        position: { x: 380, y: 40 },
        size: { width: 280, height: 180 },
        cornerRadius: 20,
        hasShadow: true,
        hasBorder: true,
        accentColor: '#111111',
        bgStyle: 'solid',
        textColor: '#FFFFFF',
        fontFamily: 'syne',
        fontSize: 22,
        fontWeight: 'black',
        isUppercase: true,
        letterSpacing: 'wide',
        textAlign: 'center',
        tags: ['Design', 'Studio', 'Aesthetics'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'node-affirmation-becoming',
        boardId: 'board-aesthetic-life',
        type: 'quote',
        title: 'Affirmation',
        content: 'I am becoming everything I choose to be.',
        quoteAuthor: 'Self',
        position: { x: 680, y: 40 },
        size: { width: 250, height: 180 },
        cornerRadius: 20,
        hasShadow: true,
        hasBorder: false,
        accentColor: '#f472b6',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'node-forest-lofi',
        boardId: 'board-aesthetic-life',
        type: 'audio',
        title: 'Forest Lo-Fi',
        subtitle: 'Ambient focus track',
        imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=800&auto=format&fit=crop',
        audioDuration: '02:45',
        position: { x: 950, y: 40 },
        size: { width: 200, height: 200 },
        cornerRadius: 20,
        hasShadow: true,
        hasBorder: false,
        accentColor: '#10b981',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'node-travel-map',
        boardId: 'board-aesthetic-life',
        type: 'map',
        title: 'TRAVEL MAP',
        subtitle: 'Global Wanderlust',
        position: { x: 60, y: 280 },
        size: { width: 320, height: 240 },
        cornerRadius: 20,
        hasShadow: true,
        hasBorder: false,
        accentColor: '#0ea5e9',
        tags: ['Travel', 'Expeditions'],
        mapPins: [
          { id: 'pin-1', title: 'New York', lat: 40.7128, lng: -74.006, note: 'The city of dreams and endless possibilities.', imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=400&auto=format&fit=crop' },
          { id: 'pin-2', title: 'Maldives', lat: 3.2028, lng: 73.2207, note: 'Overwater villa retreat.' },
          { id: 'pin-3', title: 'Tokyo', lat: 35.6762, lng: 139.6503, note: 'Design studios & neon.' },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'node-books-goal',
        boardId: 'board-aesthetic-life',
        type: 'goal',
        title: 'READ 50 BOOKS',
        subtitle: 'Annual Reading Journey',
        goalTarget: 50,
        goalCurrent: 32,
        goalUnit: 'books',
        progress: 64,
        position: { x: 400, y: 240 },
        size: { width: 290, height: 150 },
        cornerRadius: 20,
        hasShadow: true,
        hasBorder: false,
        tags: ['Discipline', 'Growth'],
        accentColor: '#3b82f6',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'node-quote-discipline',
        boardId: 'board-aesthetic-life',
        type: 'quote',
        title: '“',
        content: 'Discipline today freedom tomorrow.',
        quoteAuthor: 'Unknown',
        position: { x: 710, y: 240 },
        size: { width: 210, height: 150 },
        cornerRadius: 20,
        hasShadow: true,
        hasBorder: false,
        accentColor: '#fef08a',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 'node-learn-flutter',
        boardId: 'board-aesthetic-life',
        type: 'skill',
        title: 'LEARN FLUTTER',
        subtitle: 'Spring animation',
        content: 'Master fluid physics-based gestures and cross-platform UI systems.',
        position: { x: 940, y: 260 },
        size: { width: 260, height: 200 },
        cornerRadius: 20,
        hasShadow: true,
        hasBorder: false,
        tags: ['Flutter', 'Animation'],
        accentColor: '#60a5fa',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'board-dream-career',
    title: 'Dream Career',
    subtitle: 'Creative Leadership & Architecture',
    category: 'FAVORITES',
    icon: '🎯',
    isFavorite: true,
    theme: 'dots',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    nodes: [],
  },
  {
    id: 'board-health-wellness',
    title: 'Health & Wellness',
    subtitle: 'Daily Vitality & Mindful Living',
    category: 'PERSONAL',
    icon: '🌿',
    isFavorite: false,
    theme: 'dots',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    nodes: [],
  },
];

// Helper to load initial boards with safe schema recovery
export function loadInitialBoards(): VisionBoard[] {
  try {
    const raw = localStorage.getItem('phq_vision_boards');
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0 && typeof parsed[0] === 'object' && parsed[0]?.id) {
        return parsed.map((b: any) => ({
          ...b,
          nodes: Array.isArray(b.nodes) ? b.nodes : [],
        }));
      }
    }
  } catch (e) {
    console.warn('Could not parse phq_vision_boards:', e);
  }
  return DEFAULT_SEEDED_BOARDS;
}
